### ISSUE TITLE
A few suggestions...

### ISSUE THREAD

**Issue by chrisgoringe** [brayevalerien/Flux.1-Architecture-Diagram#1]
Thanks for this, it's amazing. A few things that would make it even better...

- the PE input isn't shown in the double block detailed diagram - I think it should be going into the RoPE attention block?

- it would be helpful if the top diagram had 'pe' and 'vec' labels, at the moment it isn't clear which is which

- maybe out of scope, but the relationship of the CLIP outputs (y and txt) to the two different text encoders would be helpful

**Comment by brayevalerien** [comment]
Thank you for your help. I'll address these issues one by one:

- You're absolutly right, I forgot to add that connection in the DoubleStream block diagram. I also forgot to connect the img_gate_1 output in the same diagram.
- Definitly, I've added labels for this. Maybe there is a way to make it clearer, but for this draft I think it's ok to do it this way. Color coding could be a more visual solution.
- This is a mistake on my part, y and txt are simply the respective output of CLIP and T5.

I have updated the diagram according to these points.
