### ISSUE TITLE
Fix: Q,K,V concat

### ISSUE THREAD

**Issue by ryan-seungyong-lee** [brayevalerien/Flux.1-Architecture-Diagram#2]
First of all, thanks for sharing your nice work and it really help me to understand the overall architecture of FLUX.1.
Anyway, I found a tiny error from your figure.

From [this](https://github.com/black-forest-labs/flux/blob/87f6fff727a377ea1c378af692afb41ae84cbe04/src/flux/modules/layers.py#L176), `txt_q` concatenates with `img_q` and same for K and V.

![Err](https://github.com/user-attachments/assets/59bcb800-d1c3-4741-94ba-d916b4f413fd)

In the figure it's not. I think you just made a typo.

Thanks.

**Comment by brayevalerien** [comment]
Yes you're right. It's an arrow typo, both Q output should point to the same concat node and same for K and V.

Thank you for repporting this issue, I'll fix the draft as soon as possible.
